mutation createUrlAlias(
$path:String!,
$isActive:Boolean,
$articleId:ID
){
  createUrlAlias(
    path:$path,
    isActive:$isActive,
    articleId:$articleId
  ){
    id
    path
    article{
      id
    }
  }
}
