#import './pageTemplateFragment.gql'

mutation createPageTemplate(
$title:String!
$body:String
$bodyJson:Json
$languageKey:LANGUAGE_KEY!
$key:String!
$type:PAGE_TEMPLATE_TYPE!
){
  createPageTemplate(
    title:$title
    body:$body
    languageKey:$languageKey
    key:$key
    type:$type
    bodyJson:$bodyJson
  ){
    ...pageTemplate
  }
}
